# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      DOCKER_IMAGE_REP: 'balangandio/prevejo-android'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: $(DOCKER_IMAGE_REP)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile-android'
        tags: 'latest'

    - script: echo $(DOCKER_IMAGE_REP) > docker_image_rep.txt
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'docker_image_rep.txt'
        ArtifactName: 'drop'