FROM kusumoto/docker-ionic-android-sdk:latest as ionic

WORKDIR /ionicapp

COPY . /ionicapp

RUN ionic cordova build android --prod

FROM alpine:3.10.2 as alpine

COPY --from=ionic /ionicapp/platforms/android/app/build/outputs/apk /outputs
